# Generated by Django 4.2.4 on 2023-09-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaifuStatsCard',
            new_name='Item',
        ),
    ]
